### ISSUE TITLE
Changing J and K buttons

### ISSUE THREAD

**Issue by nilsi01** [mattstermiller/koffee#136]
Due to us in western countries writing from left to right, and top to bottom I think it would be great to inverse the functions of the J and K keys. J should go up and K should go down imo. The way it is currently always confuses the hell out of me. Otherwise it would of course be cool to allow the user to change keyboard shortcuts individually too :) 
Thanks for your work

**Comment by mattstermiller** [comment]
Hello, thank you for your interest! I know exactly what you mean. When I first starting learning VIM keybindings, it seemed exactly backwards to me as well. Typically when user interfaces have keys/buttons in a horizontal layout, the left side is up/previous and right side is down/next. However, I didn't remap the keys and stuck with it. It took about a week of focused effort, but I trained my brain to use the default keys and soon I didn't have to think about it, it became muscle memory... which is the whole point of VIM.

This project tries to stay true to VIM keybindings so that those familiar with it will feel right at home, so I'm not going to change the defaults. I believe in making software configurable, though, so I do have plans to make the key bindings easily reconfigurable in issue #15. My time to work on this project is rather limited, so before I can make the editor for keybindings I will probably add it to the config file so at least it can be edited there. In the meantime, you can pull the code, modify [the bindings](https://github.com/mattstermiller/koffee/blob/a133e97b7f3eafc0e8ea9a19fd8362a78add8f53/src/Koffee/KeyBinding.fs#L11C1-L12C22), and [build it from the source](https://github.com/mattstermiller/koffee#from-source), which is easier than it might sound. However, before you go down that route, please keep reading...

H/J/K/L movement has a long history and plenty of modern interfaces use it - GitHub itself, Gmail, GitKraken, and many others. The specific reason for J/K bindings being the way they are has probably to due with the fact that J falls under your strong index finger, which can mash that button quickly and easily all day long, while K falls under your middle finger which typically is less strong and dexterous. So you may want to reconsider which finger you want to train to go down, which is the main movement you use. On top of that, reconsider changing this important default so that you can naturally use any other interfaces which have adopted HJKL that aren't reconfigurable, rather than being frustrated that it's backwards to you. I get it - training your brain on this is difficult, but for me it was well worth the effort. The learning curve on VIM in general is pretty steep, but once you achieve that muscle memory you'll never look back.
