### ISSUE TITLE
Publish on Chocolatey

### ISSUE THREAD

**Issue by adam-c-anderson** [mattstermiller/koffee#64]
Would love to see this project published and available through [Chocolatey](https://chocolatey.org)

**Comment by mattstermiller** [comment]
Good idea! I'll try to get this done in the next week or two.

**Comment by Boggin** [comment]
[Scoop](https://github.com/lukesampson/scoop) is also popular now. :)

**Comment by mattstermiller** [comment]
I never heard of it. It looks easy, so I should be able to include that as
well

**Comment by mattstermiller** [comment]
@adam-c-anderson Okay, so "next week or two" was really optimistic, but two months later I'm happy to report that I've submitted the latest release (0.4.1) to the Chocolatey community repo (human review pending). Since Koffee is portable, I created it as an embedded package that runs out of the Chocolatey folder, which seems to work well. Let me know if you think I should make a non-portable package as well that installs to Program Files. I've updated my release script to create packages for future releases to keep them coming.

After finally trying it out, I'm impressed by Chocolatey and will definitely start using it. Thanks for the idea.

**Comment by mattstermiller** [comment]
@boggin Scoop is cool because it's really simple compared to Chocolatey. It looks like all I have to do is create a manifest, but I want to spend some time familiarizing myself with the system and do some testing before I release anything. Thanks for the idea.

**Comment by adam-c-anderson** [comment]
😍 
Just installed it with `cinst koffee` 🎉

**Comment by mattstermiller** [comment]
@Boggin koffee is now in the scoop "extras" bucket! :tada: Scoop is really cool, thanks for the tip!
