### ISSUE TITLE
Drag'n'drop files into Koffee

### ISSUE THREAD

**Issue by jilleJr** [mattstermiller/koffee#90]
Found myself expecting drag'n'drop to work multiple times now while using Koffee. Would be nice to have.

Setting the [`AllowDrop="true"`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.uielement.allowdrop?view=netframework-4.5.1) and listening to the [`Drop`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.uielement.drop?view=netframework-4.5.1) event seems to be the way to go.

Listening for the events and then doing some basic file transfer. For example:

- move the file if source is a Koffee instance or windows Explorer
- copy the file otherwise

Then to allow dragging file out from Koffee out into other applications, that should probably get it's own issue but this seems to be a good source: https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/drag-and-drop-overview?view=netframeworkdesktop-4.8

For fun I did a basic test:

```fsharp
        window.ItemGrid.Drop.Add (fun x ->
            System.Diagnostics.Trace.WriteLine(String.Empty)

            System.Diagnostics.Trace.WriteLine("Data formats:")
            x.Data.GetFormats() |> Array.iteri (fun i f ->
                System.Diagnostics.Trace.WriteLine(sprintf "%i: %s" i f)
            )

            if x.Data.GetDataPresent(System.Windows.DataFormats.FileDrop) then
                let files = x.Data.GetData(System.Windows.DataFormats.FileDrop) :?> string[]
                System.Diagnostics.Trace.WriteLine("Files:")
                files |> Array.iteri (fun i f ->
                    System.Diagnostics.Trace.WriteLine(sprintf "%i: %s" i f)
                )

            System.Diagnostics.Trace.WriteLine(String.Empty)
        )
```

(example based on https://stackoverflow.com/a/5663329)

Result:

![koffee-drag-files](https://user-images.githubusercontent.com/2477952/95251081-4f269580-081b-11eb-9be8-e87996a68c36.gif)

Also tested it with draggin files from within a zip file opened with 7-zip and dragging downloaded file from chrome into it

![koffee-drag-files-from-chrome](https://user-images.githubusercontent.com/2477952/95251434-d5db7280-081b-11eb-8d61-a3ad08cc5159.gif)

Excuse my exitement, it's my first time coding F# with VinylUI, and except some school assignments it's also my first time coding in WPF. For some reason this is really exiting :)

**Comment by mattstermiller** [comment]
That's awesome! I've found this to be a fun project and glad you find it exciting as well.

Yes, drag'n'drop is definitely a missing feature and I'm not sure why I hadn't really considered it up to this point. It's important for interacting with the rest of windows. One of my more frequent use cases for the "escape hatch" to open Windows Explorer is to drag a file into gmail to attach it to an email, but like you said, that should probably be a separate issue from this one - dragging files into Koffee.

You'll want to create a new Event value to represent the action of dragging an item into Koffee. It will need the path of the item and which ModifierKeys are pressed so that we can replicate Explorer move/copy behavior. Even though it's possible to drag items on top of a folder in Koffee, I think it would be better and more consistent for the target to always be the current location. Then wire that Drop event to map to this new event value and handle in the controller.

**Comment by mattstermiller** [comment]
To elaborate on the move/copy behavior of Explorer that I'd like to see replicated in Koffee, here's how it works:

- Dragging a file/folder to any path on the same drive as the source moves it
- Dragging a file/folder to any path on a different drive as the source copies it
- Holding Ctrl overrides it to copy
- Holding Shift overrides it to move
- Holding Ctrl + Shift creates a shortcut instead
