### ISSUE TITLE
Add repeat count for commands

### ISSUE THREAD

**Issue by jilleJr** [mattstermiller/koffee#98]
Here's a key binding I'm used to in vim, and I'm missing this behaviour in Koffee:

- Pressing `5j` moves 5 times down.
- Pressing `3u` undos 3 times.
- Pressing `7<Del>` deletes 7 files

Could naively add so the keybindings does an actual for loop and runs the scripts x number of times.
Maybe better would be to have the keybindings to optionally handle counts, so that `3f` doesn't try to find a file 3 times, but instead just ignores the count.

**Comment by mattstermiller** [comment]
This makes sense for navigation. Especially going up (h) and back and forward (H and L) would benefit from this, as Koffee could go directly there instead of loading all the intermediate paths. Looking through the list of commands, the only other ones that I think should support it is the commands that move the cursor up and down (j, k, c-j, c-k) and maybe Go To Next Find Match (;).

I don't think that file operations should support repetition this way. It seems dangerous and clunky to allow easily repeating potentially destructive operations. This next release will support multi-select #14 to allow operating on multiple files at once in a clear, intentional way.

**Comment by jilleJr** [comment]
Good analysis! I'm going to try implement it for the commands you mentioned if that's OK

**Comment by mattstermiller** [comment]
Of course! Thanks.
